### ISSUE TITLE
Diseño de MockUps 

### ISSUE THREAD

**Issue by WilliamA-Software** [WilliamA-Software/Grupo3-Ciclo4#19]
Diseño de los Mock-Ups para el detalle de los productos y el medio en donde van a ser mostrados (recyclerview)

**Comment by fasadif** [comment]
![Mockup LUMA - Sprint 3](https://user-images.githubusercontent.com/75078387/126908590-a4f9cc13-2fdb-4c01-a569-1449d6e2c4a4.jpeg)
