### ISSUE TITLE
Mockups del carrito y favoritos

### ISSUE THREAD

**Issue by WilliamA-Software** [WilliamA-Software/Grupo3-Ciclo4#26]
Hacer un mockup de la actividad que me muestre los productos que el usuario ha agregado al carrito de compras teniendo la opción de que el usuario pague el valor total de la compra y mockup de los favoritos.

**Comment by fasadif** [comment]
![WhatsApp Image 2021-07-31 at 5 02 02 PM](https://user-images.githubusercontent.com/75078387/127753505-cb9e38c3-12da-47d3-9100-fa351a38cced.jpeg)

**Comment by fasadif** [comment]
El Mockup de los favoritos sera igual a la actividad HOME en la que se muestran los productos en forma de GRID y se usa el fragment_product_individual.xml actualizado de la rama: shopping_cart
